createOrReplace

	ref table _Measures

		measure UserWithOvertime =
				
				COUNTROWS(
				FILTER(
				SUMMARIZE(
				Dim_User_Targets,
				Dim_User_Targets[User Name],
				Dim_User_Targets[Excel_Dim_User.Overtime Hrs]
				),Dim_User_Targets[Excel_Dim_User.Overtime Hrs]>0)
				)
			formatString: 0
			lineageTag: ead14669-02d7-42e3-8463-729238273595

